<?php

namespace AppBundle\Repository;

/**
 * CanchasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanchasRepository extends \Doctrine\ORM\EntityRepository
{
}
