<?php

namespace AppBundle\Repository;

/**
 * ModuloHoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuloHoraRepository extends \Doctrine\ORM\EntityRepository
{
}
