<?php

namespace AppBundle\Repository;

/**
 * PartidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartidosRepository extends \Doctrine\ORM\EntityRepository
{
}
